# File: src/main/resources/config.yml

# MobDropHopper: which mob-drop items to collect
mobhopper:
  # Bukkit Material names, or '*' for any
  allowed_materials:
    - '*'

# CropHopper: which fully-grown crop drops to collect
crophopper:
  allowed_materials:
    - WHEAT
    - CARROT
    - POTATO
    - BEETROOT

# AutoSellChest: which chest contents to sell
autosell:
  allowed_materials:
    - DIAMOND
    - EMERALD
    - GOLD_INGOT
    # - '*'   # uncomment this line to sell everything
  tax: 0.50
  shop-category: 'default'
  interval: 10

# XPHopper: which XP-containing items (e.g. bottles) to fill
xphopper:
  allowed_items:
    - EXPERIENCE_BOTTLE
    - POTION  # if you want custom-potion behavior
